<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

use function Ramsey\Uuid\v1;

class QuoteFormInformation extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'company_name' => 'required|max:100',
            'firstname' => 'required|max:100',
            'lastname' => 'required|max:100',
            'address' => 'required',
            'city' => 'required|max:50',
            'states' => 'required',
            'phone_number' => 'required',
            'fax_number' => 'nullable',
            'email_address' => 'required|email|max:50',
            'personal_website' => 'nullable|max:50',
            'contractor_license' => 'required',
            'gl_profession' => 'required',
            'gl_residential' => 'required',
            'gl_commercial' => 'required',
            'gl_new_construction' => 'required',
            'gl_repair_remodel' => 'required',
            'gl_descops' => 'required',
            'gl_cost_proj_5years' => 'nullable|max:20',
            'gl_annual_gross' => 'required|max:20',
            'gl_no_field_emp' => 'required|max:3',
            'gl_payroll_amt' => 'required|max:20',
            'gl_using_subcon' => 'required',
            'gl_subcon_cost' => 'nullable|max:20',
            'gl_no_losses_5years' => 'required',
            'gl_explain_losses' => 'nullable',
            'wc_no_of_profession' => 'required',
            'wc_profession_1' => 'required|max:20',
            'wc_annual_payroll_1' => 'required|max:20',
            'wc_fulltime_1' => 'required|max:3',
            'wc_parttime_1' => 'required|max:3',
            'wc_profession_2' => 'nullable|max:20',
            'wc_annual_payroll_2' => 'nullable|max:20',
            'wc_fulltime_2' => 'nullable|max:3',
            'wc_parttime_2' => 'nullable|max:3',
            'wc_profession_3' => 'nullable|max:20',
            'wc_annual_payroll_3' => 'nullable|max:20',
            'wc_fulltime_3' => 'nullable|max:3',
            'wc_parttime_3' => 'nullable|max:3',
            'wc_profession_4' => 'nullable|max:20',
            'wc_annual_payroll_4' => 'nullable|max:20',
            'wc_fulltime_4' => 'nullable|max:3',
            'wc_parttime_4' => 'nullable|max:3',
            'wc_profession_5' => 'nullable|max:20',
            'wc_annual_payroll_5' => 'nullable|max:20',
            'wc_fulltime_5' => 'nullable|max:3',
            'wc_parttime_5' => 'nullable|max:3',
            'wc_profession_6' => 'nullable|max:20',
            'wc_annual_payroll_6' => 'nullable|max:20',
            'wc_fulltime_6' => 'nullable|max:3',
            'wc_parttime_6' => 'nullable|max:3',
            'wc_profession_7' => 'nullable|max:20',
            'wc_annual_payroll_7' => 'nullable|max:20',
            'wc_fulltime_7' => 'nullable|max:3',
            'wc_parttime_7' => 'nullable|max:3',
            'wc_profession_8' => 'nullable|max:20',
            'wc_annual_payroll_8' => 'nullable|max:20',
            'wc_fulltime_8' => 'nullable|max:3',
            'wc_parttime_8' => 'nullable|max:3',
            'wc_gross_receipt' => 'required|max:20',
            'wc_does_hire_subcon' => 'required',
            'wc_subcon_cost_year' => 'nullable|max:20',
            'wc_num_of_empl' => 'required|max:3',
            'wc_name' => 'required|max:255',
            'wc_title_relationship' => 'required|max:255',
            'wc_ownership_perc' => 'required',
            'wc_exc_inc' => 'required',
            'wc_ssn' => 'required',
            'wc_fein' => 'required',
            'wc_dob' => 'required|date',
            'auto_add_vehicle' => 'required',
            'auto_vehicle_year_1' => 'required|max:4',
            'auto_vehicle_maker_1' => 'required|max:100',
            'auto_vehicle_model_1' => 'required|max:100',
            'auto_vehicle_vin_1' => 'required|max:100',
            'auto_vehicle_garage_add_1' => 'required',
            'auto_vehicle_coverage_limits_1' => 'required',
            'auto_vehicle_year_2' => 'nullable|max:4',
            'auto_vehicle_maker_2' => 'nullable|max:100',
            'auto_vehicle_model_2' => 'nullable|max:100',
            'auto_vehicle_vin_2' => 'nullable|max:100',
            'auto_vehicle_garage_add_2' => 'nullable',
            'auto_vehicle_coverage_limits_2' => 'nullable',
            'auto_vehicle_year_3' => 'nullable|max:4',
            'auto_vehicle_maker_3' => 'nullable|max:100',
            'auto_vehicle_model_3' => 'nullable|max:100',
            'auto_vehicle_vin_3' => 'nullable|max:100',
            'auto_vehicle_garage_add_3' => 'nullable',
            'auto_vehicle_coverage_limits_3' => 'nullable',
            'auto_vehicle_year_4' => 'nullable|max:4',
            'auto_vehicle_maker_4' => 'nullable|max:100',
            'auto_vehicle_model_4' => 'nullable|max:100',
            'auto_vehicle_vin_4' => 'nullable|max:100',
            'auto_vehicle_garage_add_4' => 'nullable',
            'auto_vehicle_coverage_limits_4' => 'nullable',
            'auto_vehicle_year_5' => 'nullable|max:4',
            'auto_vehicle_maker_5' => 'nullable|max:100',
            'auto_vehicle_model_5' => 'nullable|max:100',
            'auto_vehicle_vin_5' => 'nullable|max:100',
            'auto_vehicle_garage_add_5' => 'nullable',
            'auto_vehicle_coverage_limits_5' => 'nullable',
            'auto_vehicle_year_6' => 'nullable|max:4',
            'auto_vehicle_maker_6' => 'nullable|max:100',
            'auto_vehicle_model_6' => 'nullable|max:100',
            'auto_vehicle_vin_6' => 'nullable|max:100',
            'auto_vehicle_garage_add_6' => 'nullable',
            'auto_vehicle_coverage_limits_6' => 'nullable',
            'auto_vehicle_year_7' => 'nullable|max:4',
            'auto_vehicle_maker_7' => 'nullable|max:100',
            'auto_vehicle_model_7' => 'nullable|max:100',
            'auto_vehicle_vin_7' => 'nullable|max:100',
            'auto_vehicle_garage_add_7' => 'nullable',
            'auto_vehicle_coverage_limits_7' => 'nullable',
            'auto_vehicle_year_8' => 'nullable|max:4',
            'auto_vehicle_maker_8' => 'nullable|max:100',
            'auto_vehicle_model_8' => 'nullable|max:100',
            'auto_vehicle_vin_8' => 'nullable|max:100',
            'auto_vehicle_garage_add_8' => 'nullable',
            'auto_vehicle_coverage_limits_8' => 'nullable',
            'auto_add_driver' => 'required',
            'auto_add_drivers_name_1' => 'required|max:100',
            'auto_add_driver_lic_1' => 'required|max:50',
            'auto_add_driver_mileage_radius_1' => 'required|max:100',
            'auto_add_driver_date_birth_1' => 'required|date',
            'auto_add_driver_civil_status_1' => 'required',
            'auto_add_driver_spouse_name_1' => 'required|max:100',
            'auto_add_driver_spouse_dob_1' => 'required|date',
            'auto_add_drivers_name_2' => 'nullable|max:100',
            'auto_add_driver_lic_2' => 'nullable|max:50',
            'auto_add_driver_mileage_radius_2' => 'nullable|max:100',
            'auto_add_driver_date_birth_2' => 'nullable|date',
            'auto_add_driver_civil_status_2' => 'nullable',
            'auto_add_driver_spouse_name_2' => 'nullable|max:100',
            'auto_add_driver_spouse_dob_2' => 'nullable|date',
            'auto_add_drivers_name_3' => 'nullable|max:100',
            'auto_add_driver_lic_3' => 'nullable|max:50',
            'auto_add_driver_mileage_radius_3' => 'nullable|max:100',
            'auto_add_driver_date_birth_3' => 'nullable|date',
            'auto_add_driver_civil_status_3' => 'nullable',
            'auto_add_driver_spouse_name_3' => 'nullable|max:100',
            'auto_add_driver_spouse_dob_3' => 'nullable|date',
            'auto_add_drivers_name_4' => 'nullable|max:100',
            'auto_add_driver_lic_4' => 'nullable|max:50',
            'auto_add_driver_mileage_radius_4' => 'nullable|max:100',
            'auto_add_driver_date_birth_4' => 'nullable|date',
            'auto_add_driver_civil_status_4' => 'nullable',
            'auto_add_driver_spouse_name_4' => 'nullable|max:100',
            'auto_add_driver_spouse_dob_4' => 'nullable|date',
            'bond_owners_name' => 'required|max:100',
            'bond_owners_ssn' => 'required',
            'bond_owners_dob' => 'required|date',
            'bond_owners_civil_status' => 'required',
            'bond_owners_spouse_name' => 'nullable|max:100',
            'bond_owners_spouse_dob' => 'nullable|date',
            'bond_owners_spouse_ssn' => 'nullable',
            'bond_type_bond_requested' => 'required|max:100',
            'bond_amount_of_bond' => 'required|max:20',
            'bond_term_of_bond' => 'required',
            'bond_type_of_license' => 'required',
            'bond_if_other_type_of_license' => 'nullable',
            'bond_license_or_application_no' => 'required|max:100',
            'bond_effective_date' => 'required',
            'excess_limits' => 'required|max:20',
            'excess_gl_eff_date' => 'required|date',
            'excess_no_losses_5years' => 'required',
            'excess_explain_losses' => 'nullable',
            'excess_insurance_carrier' => 'required|max:100',
            'excess_policy_or_quote_no' => 'required|max:50',
            'excess_policy_premium' => 'required|max:20',
            'excess_effective_date' => 'required|date',
            'excess_expiration_date' => 'required|date',
            'tools_misc_tools' => 'required',
            'tools_rented_or_leased_amt' => 'required',
            'tools_sched_equipment' => 'required',
            'tools_equipment_type' => 'required|max:100',
            'tools_equipment_year' => 'required|max:4',
            'tools_equipment_make' => 'required|max:100',
            'tools_equipment_model' => 'required|max:100',
            'tools_equipment_vin_or_serial_no' => 'required|max:100',
            'tools_equipment_valuation' => 'required|max:100',
            'tools_no_losses_5years' => 'required',
            'tools_explain_losses' => 'nullable',
            'br_property_address' => 'required',
            'br_value_of_existing_structure' => 'required|max:20',
            'br_value_of_work_performed' => 'required|max:20',
            'br_period_duration_project' => 'required|max:20',
            'pollution_profession' => 'required',
            'pollution_residential' => 'required',
            'pollution_commercial' => 'required',
            'pollution_new_construction' => 'required',
            'pollution_repair_remodel' => 'required',
            'pollution_descops' => 'required',
            'pollution_cost_proj_5years' => 'nullable|max:20',
            'pollution_annual_gross' => 'required|max:20',
            'pollution_no_field_emp' => 'required|max:3',
            'pollution_payroll_amt' => 'required|max:20',
            'pollution_using_subcon' => 'required',
            'pollution_subcon_cost' => 'nullable|max:20',
            'pollution_no_losses_5years' => 'required',
            'pollution_explain_losses' => 'nullable',
            'ayc_bop' => 'required',
            'ayc_date_business_started' => 'required|date',
            'ayc_yrs_exp_contractor' => 'required',
            'ayc_owners_first_name' => 'required',
            'ayc_owners_last_name' => 'required',
            'ayc_phone_number' => 'required'
        ];
    }
}